# Generated by Django 4.2.6 on 2023-11-29 10:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('droppin', '0003_contactor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('category_post', models.CharField(choices=[('Graphics_Design', 'Graphics_Design'), ('Web_Design', 'Web_Design'), ('Marketing_Digital', 'Marketing_Digital'), ('Transformation_Digitale', 'Transformation_Digitale'), ('Video_Surveillance', 'Video_Surveillance')], max_length=200)),
                ('title_post', models.CharField(max_length=200, null=True)),
                ('rated_post', models.CharField(max_length=200, null=True)),
                ('capacity_post', models.CharField(choices=[('40%', '40%'), ('75%', '75%'), ('80%', '80%'), ('85%', '85%'), ('95%', '95%'), ('100%', '100%')], max_length=200)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('author_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='droppin.customer')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
    ]
