# Generated by Django 4.2.6 on 2023-11-29 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('droppin', '0004_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='description_post',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
