# Generated by Django 4.2.6 on 2023-11-30 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('droppin', '0005_post_description_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commentor',
            fields=[
                ('cmt_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('cmt_name', models.CharField(max_length=200, null=True)),
                ('cmt_address', models.CharField(max_length=200, null=True)),
                ('cmt_description', models.CharField(max_length=200, null=True)),
                ('cmt_time', models.DateTimeField(max_length=200, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
    ]
